Abilis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account import views
from django.conf.urls import url


from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'users', views.UserList)
router.register(r'Dcategory', views.DocumentCategoryList)
router.register(r'subcategory', views.categoryList)
router.register(r'documentation',views.DocumentationList)
router.register(r'forum_question', views.QuestionList)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout_user, name='logout'),

    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
         name= 'password_change'),

    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
         name ='password_change_done'),

    path('document/',include('account.urls')),
    path('dashboard/',include('account.urls')),
    path('userlist/', include('account.urls')),

    path('category/', include('account.urls')),

    path('doc_category/', include('account.urls')),

    path('password/', include('account.urls')),
    path('forum/', include('account.urls')),
    url(r'^api/', include(router.urls)),

    path('api/Validusers/', views.UserLogin),
    # path('Documentation/', views.UserLogin),
    url(r'^api/search/(?P<category>.+)/$', views.SearchList.as_view()),
    path('api/user_question_list/<int:id>/', views.get_user_question, name='user_question_list'),
    path('api/answer_list/<int:id>/', views.get_answer_list, name="get_answer_list"),
    path('api/question_answer_list/', views.question_answer_list),
    path('api/question_list/', views.api_question_list),
    path('answer_list_dashboard/', views.answer_list, name="answer_list_dashboard"),
    url(r'^api/searchall/(?P<category>.+)/$', views.SearchListAll.as_view()),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from .import views
from django.urls import path


from django.conf.urls import url , include




urlpatterns = [
    url(r'^document/$', views.document_list, name='document_list'),
    url(r'^document/new/$', views.document_new, name='document_new'),
    url(r'^document/(?P<pk>[0-9]+)/edit/$', views.document_edit, name='document_edit'),
    url(r'^document/(?P<pk>[0-9]+)/delete/$', views.document_delete, name='document_delete'),
    url(r'^category/$', views.list_category, name='list_category'),
    url(r'^category/new/$', views.add_category, name='add_category'),
    # url(r'^category/(?P<pk>[0-9]+)/edit/$', views.edit_category, name='edit_category'),
    url(r'^category/(?P<pk>[0-9]+)/delete/$', views.delete_category, name='delete_category'),
    url(r'^doc_list/$', views.list_document_category, name='list_document_category'),
    url(r'^doc_list/new/$', views.add_document_category, name='add_document_category'),
    # url(r'^category/(?P<pk>[0-9]+)/edit/$', views.edit_category, name='edit_category'),
    url(r'^doc_list/(?P<pk>[0-9]+)/delete/$', views.delete_document_category, name='delete_document_category'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^userlist/$', views.userList, name='userlist'),
    path('question_list/', views.question_list, name='question_list'),
    path('answer_list/', views.answer_list, name='answer_list'),

    path('question_answer/<int:id>/', views.question_answer, name='question_answer'),
    path('question_delete/<int:id>/', views.question_delete, name='question_delete'),
    path('answer_delete/<int:id>/', views.answer_delete, name='answer_delete'),

]

account/models.py
from django.db import models
from django.utils import timezone

#from multiselectfield import MultiSelectField
# from multiselectfield import MultiSelectField

# Create your models here.


class user(models.Model):
    name = models.CharField(max_length=100, default='')
    username = models.CharField(max_length=100, default='')
    email = models.EmailField()
    password = models.CharField(max_length=100 , default='')
    error = models.BooleanField(default='False')
    registration_id = models.CharField(max_length=1000)


class DocumentCategory(models.Model):
    doc_category = models.CharField(max_length=200, default='')

    def __str__(self):
        return self.doc_category


class Category(models.Model):
    new_category = models.CharField(max_length=200, default='')

    def __str__(self):
        return self.new_category


class Documentation(models.Model):
    # MY_CHOICES = (
    #     ('a', "A good choice"),
    #     ('b', "A bad choice"),
    #     ('c', "A noice choice"),
    #     ('d', "A Tori choice"),
    # )
    doc_category = models.CharField(max_length=100, default='')
    title = models.CharField(max_length=100, default='')
    date = models.DateField()
    category = models.ManyToManyField(Category)
    document = models.FileField(upload_to='documents', default='', blank=True)
    description = models.TextField(max_length=500, default='')
    information = models.TextField(max_length=5000, default='', blank=True)
    info_file = models.FileField(upload_to='files', default='', blank=True)


class Form_question(models.Model):
    user = models.ForeignKey(user, on_delete=models.CASCADE)
    question = models.CharField(max_length=250)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.question


class Form_answer(models.Model):
    answer = models.CharField(max_length=240)
    question = models.ForeignKey(Form_question, on_delete=models.CASCADE)

account/forms.py
from django import forms
# from multiselectfield import MultiSelectFormField

from .models import Documentation, Category, DocumentCategory, Form_answer



class DocumentationForm(forms.ModelForm):
    class Meta:
        model = Documentation
        fields = ('title', 'date', 'doc_category', 'document', 'description', 'information', 'info_file')

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('new_category',)


class DocumentNewForm(forms.ModelForm):
    class Meta:
        model = DocumentCategory
        fields = ('doc_category',)


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Form_answer
        fields = ('answer', )

account/views.py
from django.shortcuts import render
from .models import *
from .forms import DocumentationForm, CategoryForm, DocumentNewForm, AnswerForm
from django.shortcuts import get_object_or_404
# from django.contrib import auth
# from django.contrib import messages
from django.contrib.auth import logout

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib.auth.forms import PasswordChangeForm
from django.core.files import File
from fcm_django.models import FCMDevice

import os

from rest_framework import viewsets
from .serializers import *


from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.core import serializers
import json


from django.views import generic

from rest_framework import generics
# from django.db.models import Q
from rest_framework.response import Response
from functools import reduce
import operator
from django.db.models import Q

# Pagination
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



from django.http import JsonResponse

# Create your views here.

@login_required(login_url='login')
def document_list(request):
    document = Documentation.objects.all()

    page = request.GET.get('page', 1)

    paginator = Paginator(document, 10)

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    return render(request, 'documents/document_list.html', context={'document': users})


@login_required(login_url='login')
def document_new(request):
    if request.method == "POST":
        form = DocumentationForm(request.POST, request.FILES or None)
        if form.is_valid():
            document = form.save(commit=False)
            doc = form.cleaned_data['information']
            file_title = form.cleaned_data['title']
            cr = open(file_title + '.txt', 'w')
            cr.write(doc)
            cr.close()
            cr = open(file_title + '.txt', 'r')
            document.info_file.save(file_title + '.txt', File(cr))
            cr.close()
            os.remove(file_title + '.txt')
            selected = request.POST.getlist('category')

            document.save()
            for cat in selected:
                category_added = Category.objects.get(new_category=cat)
                document.category.add(category_added)

            category = Category.objects.all()
            doc_category = DocumentCategory.objects.all()
            context = {'added': True, 'add_category': category, 'add_doc_category': doc_category}
            return render(request, 'documents/document_add.html', context)
        else:
            print(form.errors)

    else:
        form = DocumentationForm()
        category = Category.objects.all()
        doc_category = DocumentCategory.objects.all()

        return render(request, 'documents/document_add.html', {'form': form, 'add_category': category, 'add_doc_category': doc_category})


@login_required(login_url='login')
def document_edit(request, pk):
    document = get_object_or_404(Documentation, pk=pk)

    if request.method == "POST":

        form = DocumentationForm(request.POST, request.FILES or None, instance=document)
        print("validated form")

        if form.is_valid():

            document = form.save(commit=False)
            document.save()
            document = Documentation.objects.all()
            context = {'added': True,'document':document}
            return render(request, 'documents/document_list.html', context)

    else:
        form = DocumentationForm(instance=document)
        category1 = Category.objects.all()
        doc_category1 = DocumentCategory.objects.all()

        return render(request, 'documents/document_edit.html', {'document': document, 'add_category': category1, 'add_doc_category': doc_category1})


@login_required(login_url='login')
def document_delete(request, pk):
    document = get_object_or_404(Documentation, pk=pk)
    document.delete()
    document = Documentation.objects.all()
    return render(request, 'documents/document_list.html', {'document': document})


@login_required(login_url='login')
def dashboard(request):
    users1 = user.objects.all()

    page = request.GET.get('page', 1)

    paginator = Paginator(users1, 10)

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    count = user.objects.all().count()
    context = {'active_users':users, 'total_users':count}
    return render(request, 'dashboard.html', context)


@login_required(login_url='login')
def userList(request):
    return render(request, 'userlist.html')


@login_required(login_url='login')
def list_category(request):
    document = Category.objects.all()

    page = request.GET.get('page', 1)

    paginator = Paginator(document, 10)

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    return render(request, 'documents/disable_category/category_list.html', context={'cat_list': users})


@login_required(login_url='login')
def add_category(request):
    if request.method == "POST":
        form = CategoryForm(request.POST, request.FILES or None)
        if form.is_valid():
            add = form.save(commit=False)
            add.save()
            category = Category.objects.all()
            doc_category = DocumentCategory.objects.all()

            context = {'catadded': True, 'add_category': category, 'add_doc_category': doc_category}

            return render(request, 'documents/document_add.html', context)
    else:
        form = CategoryForm()

    return render(request, 'documents/disable_category/category_add.html', {'from': form})

#
# def edit_category(request, pk):
#     edit = get_object_or_404(AddCategory, pk=pk)
#     if request.method == "POST":
#         form = AddCategoryForm(request.POST, request.FILES or None, instance=edit)
#         if form.is_valid():
#             edit = form.save(commit=False)
#             edit.save()
#             edit = AddCategory.objects.all()
#             context = {'added': True,'edit':edit}
#             return render(request, 'documents/document_list.html',context)
#
#     else:
#         form = AddCategoryForm(instance=edit)
#
#
#     return render(request, 'documents/document_edit.html',{'edit': edit})



@login_required(login_url='login')
def delete_category(request, pk):
    delete = get_object_or_404(Category, pk=pk)
    delete.delete()
    delete = Category.objects.all()
    return render(request, 'documents/disable_category/category_list.html', {'cat_list': delete})


@login_required(login_url='login')
def list_document_category(request):
    document = DocumentCategory.objects.all()

    page = request.GET.get('page', 1)

    paginator = Paginator(document, 10)

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)

    return render(request, 'documents/document_category/document_category_list.html', context={'doc_list': users})


@login_required(login_url='login')
def add_document_category(request):
    if request.method == "POST":
        form = DocumentNewForm(request.POST, request.FILES or None)
        if form.is_valid():
            add = form.save(commit=False)
            add.save()
            category = Category.objects.all()
            doc_category = DocumentCategory.objects.all()

            context = {'cat_added': True,'add_category': category, 'add_doc_category': doc_category}

            return render(request, 'documents/document_add.html', context)
    else:
        form = CategoryForm()

    return render(request, 'documents/document_category/document_category_add.html', {'from': form})


@login_required(login_url='login')
def delete_document_category(request, pk):
    delete = get_object_or_404(DocumentCategory, pk=pk)
    delete.delete()
    delete = DocumentCategory.objects.all()
    return render(request, 'documents/document_category/document_category_list.html', {'doc_list': delete})


def logout_user(request):
    logout(request)
    return redirect('login')



#API

# API for User
class UserList(viewsets.ModelViewSet):
    queryset = user.objects.all()
    serializer_class = userSerializer


# API for Document Category

class DocumentCategoryList(viewsets.ModelViewSet):
    queryset = DocumentCategory.objects.all()
    serializer_class = DocumentCategorySerializer


# API for Category List

class categoryList(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = categoryinfoSerializer


# API for Documentaion
class DocumentationList(viewsets.ModelViewSet):
    queryset = Documentation.objects.all()
    serializer_class = DocumentationSerializer

class QuestionList(viewsets.ModelViewSet):
    queryset = Form_question.objects.all()
    serializer_class = ForumQuestionSerializer


@csrf_exempt
def UserLogin(request):
    username = request.POST['username']
    password = request.POST['password']

    acoountuser = user.objects.filter(username =username , password = password)
    if acoountuser :
        mainuser = user.objects.get(username = username)

        # data = serializers.serialize('json', [mainuser, ])
        #
        # struct = json.loads(data)
        # data = json.dumps(struct[0])
        # return HttpResponse(data, content_type='json', status=200)
        # return JsonResponse({'error': 'False'}, status=401)

        data = userSerializer(mainuser)
        return JsonResponse(data.data, status=201)
    else:
        return JsonResponse({'error': True}, status=401)


def question_list(request):

account/templates/documents/category_list.html
{% extends 'home.html' %}

{% block content %}
<div id="page-content-wrapper">
    <div class="section-wrapper">
        <h3 class="text-center"> Category List</h3>
    </div>
    <div class="section-wrapper">
        <table class="table table-responsive">
            <thead>
            <tr>

                <th>Category</th>
                <th>Action</th>


            </tr>
            </thead>

                {% for cat_list in cat_list %}

                    <tbody>
                    <tr>
                        <td>{{ cat_list.new_category }}</td>



                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false">
                                    Action
                                </button>
                                <div class="dropdown-menu">
{#                                    <a class="dropdown-item" href="{% url 'edit_category' pk=catlist.pk %}">Edit</a>#}
                                    <a class="dropdown-item" href="{% url 'delete_category' pk=cat_list.pk %}"
                                       onclick="return confirm('Are you sure?')">Delete</a>

                                </div>
                            </div>
                        </td>


                    </tr>
                    </tbody>

                {% endfor %}

        </table>

</div>
</div>

{% endblock %}]

account/templates/documents/document_add.html
{% extends 'home.html' %}

{% load staticfiles %}

{% block content %}

      {% if added %}
                <script>alert("Document Added")</script>
            {% endif %}


<div id="page-content-wrapper">
    <div class="section-wrapper">
        <h3 class="text-center">Add Document</h3>
    </div>
    <div class="section-wrapper form-bg">
        <form method="POST" name="form"  enctype="multipart/form-data" class="form-horizontal" >{% csrf_token %}

            <div class = "form-group">
                <label for = "id_title" class = "control-label col-sm-2 ">Title*</label>
                <div class = "col-sm-4 no-outline">
                    <input type="text" id="id_title" name="title" placeholder="Title Here" required style="width: 100%">
                </div>
<!--                <div class = "col-sm-2 no-outline">-->
<!--                    <input type="text" placeholder="Middle Name">-->
<!--                </div>-->
<!--                <div class = "col-sm-2 no-outline">-->
<!--                    <input type="text" placeholder="Last Name" required>-->
                </div>
<!--            </div>-->
            <div class = "form-group">
                <label for = "id_date" class = "control-label col-sm-2 ">Date*</label>
                <div class = "col-sm-2 no-outline">
                    <input type="date" id="id_date" name="date" placeholder="Date" required>
                </div>
            </div>

{#            <div class="form-group">#}
{#                    <label for="id_category" class="control-label col-sm-2 ">Disabled Category*</label>#}
{#                    <div class="col-sm-4">#}
{#                        <select class="form-control" name="category" id="id_category" required>#}
{#                            <option value="Visually Impaired">Visually Impaired</option>#}
{#                            <option value="Hearing Impaired">Hearing Impaired</option>#}
{#                            <option value="No Leg">No Leg</option>#}
{#                        </select>#}
{#                    </div>#}
{#                </div>#}

            <div class="form-group">
                <label for="id_new_category" class="control-label col-sm-2 ">Disabled Category*</label>
                <div class="col-sm-4">
{#                    <select class="form-control" name="category" id="id_new_category" multiple = "multiple" required>#}
{#                        {% for add_category in add_category %}#}
{#                            <option value="{{ add_category.new_category }}">{{ add_category.new_category }}</option>#}
{#                        {% endfor %}#}
{#                    </select>#}
{#                    <input type ="checkbox" onclick="toggle()"/>Select All#}
                    {% for add_category in add_category %}
                    <input type="checkbox" name="category" value="{{ add_category.new_category }}" id ={{ add_category.id  }}> {{ add_category.new_category }}<br>
                   {% endfor %}
                </div>

                <div class ="col-sm-4">
                    <a class="fa fa-fw fa-plus"  href="{% url 'add_category' %}">Category</a>
                          <div class ="col-sm-4">
                                <a class="fa fa-list"  href="{% url 'list_category'  %}">list category</a>
                          </div>


           </div>
            </div>



      <div class = "form-group">
                <label for = "id_doc_category" class = "control-label col-sm-2 ">Document Category*</label>
          <div class = "col-sm-4">
                    <select  class = "form-control" name = "doc_category" id="id_doc_category" required>

                        {% for add_doc_category in add_doc_category %}


                            <option value="{{ add_doc_category.doc_category }}">{{ add_doc_category.doc_category }}</option>


                        {% endfor %}

                    </select>
                </div>

       <div class ="col-sm-4">
                    <a class="fa fa-fw fa-plus"  href="{% url 'add_document_category' %}">Category</a>
                          <div class ="col-sm-4">
                                <a class="fa fa-list"  href="{% url 'list_document_category'  %}">list category</a>
                          </div>


           </div>
            </div>

        <div class = "form-group">
                <label for = "id_description" class = "control-label col-sm-2 ">Description*</label>
                <div class = "col-sm-4 no-outline">
                    <input type="text" id="id_description" name="description" placeholder="Description Here" required  style="width: 100%">
                </div>
        </div>

          <div class = "form-group">
                <label for = "id_information" class = "control-label col-sm-2 ">Information*</label>
                <div class = "col-sm-6 no-outline">
                <textarea name="information" id="id_information"  ></textarea>
                </div>
        </div>




{# <div class="form-group">#}
{#                <label for="id_my_field" class="control-label col-sm-2 ">Choice:*</label>#}
{#                <div class="col-sm-4">#}
{#                    <select class="form-control" name="my_field" id="id_my_field" multiple = "multiple" required>#}
{#                        {% for c in form.my_field %}#}
{#                            <option value="{{ c }}">{{ c }}</option>#}
{#                        {% endfor %}#}
{#                    </select>#}
{##}
{#                </div>#}
        <div class = "form-group">
                <div class = "col-sm-2 no-outline">
                    <input type="file" accept="application/msword" id="id_doc_category" name="document" placeholder="docs">
                </div>
            </div>
      <div class = "form-group">
                <div class = "col-sm-2 no-outline">
                    <input type="hidden"  id="id_info_file" name="info_file" >
                </div>
            </div>


            <div class = "col-sm-8">
                <input type="submit" onclick="return validateForm()" class="btn submit-btn" value="Add">
            </div>

        </form>
    </div>
</div>
    <script>

        function validateForm() {
            var x = document.forms["form"]["information"].value || document.forms["form"]["document"].value;
            console.log(x);
            if (x== "") {
                alert("Both Information and Document can't be empty");
                return false;

            }
        }
        function toggle() {
  checkboxes = document.getElementsByName('category');
  for(var i=0, n=checkboxes.length;i<n;i++) {
    checkboxes[i].checked = source.checked;
  }
}
    </script>
{% endblock %}

account/templates/documents/document_edit.html
{% extends 'home.html' %}

{% block content %}



    <div id="page-content-wrapper">
        <div class="section-wrapper">
            <h3 class="text-center">Edit Document</h3>
        </div>
        <div class="section-wrapper form-bg">
            <form method="POST" name="form" enctype="multipart/form-data" class="form-horizontal">{% csrf_token %}

                <div class="form-group">
                    <label for="id_title" class="control-label col-sm-2 ">Title*</label>
                    <div class="col-sm-4 no-outline">
                        <input type="text" id="id_title" name="title" placeholder="Title Here"
                               value="{{ document.title }}" style="width: 100%">
                    </div>
                    <!--                <div class = "col-sm-2 no-outline">-->
                    <!--                    <input type="text" placeholder="Middle Name">-->
                    <!--                </div>-->
                    <!--                <div class = "col-sm-2 no-outline">-->
                    <!--                    <input type="text" placeholder="Last Name" required>-->
                </div>
                <!--            </div>-->
                <div class="form-group">
                    <label for="id_date" class="control-label col-sm-2 ">Date*</label>
                    <div class="col-sm-2 no-outline">
                        <input type="date" id="id_date" name="date" placeholder="Date"
                               value="{{ document.date | date:'Y-m-d' }}">
                    </div>
                </div>

                {#            <div class="form-group">#}
                {#                    <label for="id_category" class="control-label col-sm-2 ">Disabled Category*</label>#}
                {#                    <div class="col-sm-4">#}
                {#                        <select class="form-control" name="category" id="id_category" required>#}
                {#                            <option value="Visually Impaired">Visually Impaired</option>#}
                {#                            <option value="Hearing Impaired">Hearing Impaired</option>#}
                {#                            <option value="No Leg">No Leg</option>#}
                {#                        </select>#}
                {#                    </div>#}
                {#                </div>#}

                <div class="form-group">
                    <label for="id_new_category" class="control-label col-sm-2 ">Disabled Category*</label>
                    <div class="col-sm-4">
                        <select class="form-control" name="category" id="id_new_category">
                            {% for add_category in add_category %}
                                {% if add_category.new_category == document.category %}

                                    <option value="{{ add_category.new_category }}"
                                            selected>{{ add_category.new_category }}</option>
                                {% else %}
                                    <option value="{{ add_category.new_category }}">{{ add_category.new_category }}</option>
                                {% endif %}

                            {% endfor %}
                        </select>

                    </div>


                </div>


                <div class="form-group">
                    <label for="id_doc_category" class="control-label col-sm-2 ">Document Category*</label>
                    <div class="col-sm-4">
                        <select class="form-control" name="doc_category" id="id_doc_category">

                            {% for add_doc_category in add_doc_category %}
                                {% if add_doc_category.doc_category == document.doc_category %}


                                    <option value="{{ add_doc_category.doc_category }}"
                                            selected>{{ add_doc_category.doc_category }}</option>
                                {% else %}

                                    <option value="{{ add_doc_category.doc_category }}">{{ add_doc_category.doc_category }}</option>


                                {% endif %}



                            {% endfor %}

                        </select>
                    </div>

                </div>

                <div class="form-group">
                    <label for="id_description" class="control-label col-sm-2 ">Description*</label>
                    <div class="col-sm-4 no-outline">
                        <input type="text" id="id_description" name="description" placeholder="Description Here"
                               value="{{ document.description }}" style="width: 100%">
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_information" class="control-label col-sm-2 ">Information*</label>
                    <div class="col-sm-6 no-outline">
                        <textarea name="information" id="id_information">{{ document.information }}</textarea>
                    </div>
                </div>


                <div class="form-group">

                    <div class="col-sm-2 no-outline">

                        <input type="file" accept="application/msword" id="id_doc_category" name="document"
                               placeholder="docs" value="{{ document.document }}">{{ document.document }}
                    </div>
                </div>

                <div class="col-sm-8">
                    <input type="submit" onclick="return validateForm()" class="btn submit-btn" value="Edit">
                </div>

            </form>
        </div>
    </div>
    <script>

        function validateForm() {
            var x = document.forms["form"]["information"].value || document.forms["form"]["document"].value;
            console.log(x);
            if (x == "") {
                alert("Both Information and Document can't be empty");
                return false;

            }
        }
    </script>
{% endblock %}